# Generated by Django 6.0 on 2026-03-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inf',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
